export const Types = {
  FETCH_POSTS: "FETCH_POSTS",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILED: "FETCH_POSTS_FAILED",

  DELETE_POSTS: "DELETE_POSTS",
  DELETE_POSTS_SUCCESS: "DELETE_POSTS_SUCCESS",
  DELETE_POSTS_FAILED: "DELETE_POSTS_FAILED",

  EDIT_POSTS: "EDIT_POSTS",
  EDIT_POSTS_SUCCESS: "EDIT_POSTS_SUCCESS",
  EDIT_POSTS_FAILED: "EDIT_POSTS_FAILED",

  ADD_POSTS: "ADD_POSTS",
  ADD_POSTS_SUCCESS: "ADD_POSTS_SUCCESS",
  ADD_POSTS_FAILED: "ADD_POSTS_FAILED",
};
